name: Build Docker image

on:
  push:
    tags:
      - ".*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t Ronny-Gallin-Software-Engineering/excalidraw:${{github.ref_name}} .
